language: php

php:
    - 7.1
    - 7.2
    - 7.3
    - 7.4

dist: trusty
sudo: true

before_script:
    - composer self-update
    - composer install --no-interaction --dev

script:
    - pwd
    - ./vendor/bin/phpunit --verbose --coverage-clover=coverage.xml

after_script:
    - bash <(curl -s https://codecov.io/bash)

notifications:
    email: true

matrix:
    fast_finish: true
